"""create_models

Revision ID: 13e0139a9e05
Revises: d647cd0fae93
Create Date: 2020-02-23 19:52:33.173793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e0139a9e05'
down_revision = 'd647cd0fae93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('date_handled', sa.Date(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('review_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'SUCCESS', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('error_summary', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('granule',
    sa.Column('uuid', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('copernicus_ingestion_date', sa.DateTime(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('downloader_job_id', sa.Integer(), nullable=True),
    sa.Column('s3_location', sa.String(length=1024), nullable=True),
    sa.Column('download_status', sa.Enum('NOT_STARTED', 'DOWNLOADING', 'SUCCESS', 'ERROR', 'INVALID', 'ARCHIVED', name='downloadstatus'), nullable=False),
    sa.ForeignKeyConstraint(['downloader_job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('job_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('log_level', sa.Enum('INFO', 'WARNING', 'ERROR', name='loglevel'), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_log')
    op.drop_table('granule')
    op.drop_table('job')
    # ### end Alembic commands ###
