"""update_log_db

Revision ID: fa116e4946ff
Revises: 13e0139a9e05
Create Date: 2020-02-23 22:59:39.017546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa116e4946ff'
down_revision = '13e0139a9e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_log', sa.Column('logged_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_log', 'logged_at')
    # ### end Alembic commands ###
