"""Update models for reviewer

Revision ID: faa685d40842
Revises: fa116e4946ff
Create Date: 2020-02-24 16:33:21.315387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa685d40842'
down_revision = 'fa116e4946ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('granule', sa.Column('checksum', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('granule', 'checksum')
    # ### end Alembic commands ###
